/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gift.of.silence.client.debug;

/**
 *
 * @author CP318674
 */
public class Gui extends javax.swing.JPanel {

    private final Debug debug;

    /**
     * Creates new form Gui
     */
    public Gui(Debug debug) {
        initComponents();
        this.debug = debug;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        traceBtn = new javax.swing.JButton();
        debugBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        warningBtn = new javax.swing.JButton();
        errorBtn = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        connectBtn = new javax.swing.JButton();
        connectionsBtn = new javax.swing.JButton();
        disconnectBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        statusLbl = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        traceBtn.setText("trace");
        traceBtn.setFocusable(false);
        traceBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        traceBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(traceBtn);

        debugBtn.setText("debug");
        debugBtn.setFocusable(false);
        debugBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        debugBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(debugBtn);

        infoBtn.setText("info");
        infoBtn.setFocusable(false);
        infoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(infoBtn);

        warningBtn.setText("warning");
        warningBtn.setFocusable(false);
        warningBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        warningBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(warningBtn);

        errorBtn.setText("error");
        errorBtn.setFocusable(false);
        errorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        errorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(errorBtn);

        add(jToolBar1, java.awt.BorderLayout.EAST);

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        connectBtn.setText("connect");
        connectBtn.setFocusable(false);
        connectBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connectBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(connectBtn);

        connectionsBtn.setText("connections");
        connectionsBtn.setFocusable(false);
        connectionsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connectionsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(connectionsBtn);

        disconnectBtn.setText("disconnect");
        disconnectBtn.setFocusable(false);
        disconnectBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disconnectBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(disconnectBtn);

        add(jToolBar2, java.awt.BorderLayout.LINE_START);

        statusLbl.setText("status");
        jPanel1.add(statusLbl);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectBtn;
    private javax.swing.JButton connectionsBtn;
    private javax.swing.JButton debugBtn;
    private javax.swing.JButton disconnectBtn;
    private javax.swing.JButton errorBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JButton traceBtn;
    private javax.swing.JButton warningBtn;
    // End of variables declaration//GEN-END:variables
}
